# примеры API-запросов

@baseUrl = http://localhost:8000/api/v1

# создание продукта
POST {{baseUrl}}/products/
Content-Type: application/json

{
  "title": "Редиска",
  "description": "Слад"
}

###

# получение продуктов
GET {{baseUrl}}/products/?ordering=id
Content-Type: application/json

###

# обновление продукта
PATCH {{baseUrl}}/products/37/
Content-Type: application/json

{
  "description": "Сладкая"
}

###

# удаление продукта
DELETE {{baseUrl}}/products/35/
Content-Type: application/json

###

# поиск продуктов по названию и описанию
GET {{baseUrl}}/products/?search=зе
Content-Type: application/json

###

# создание склада
POST {{baseUrl}}/stocks/
Content-Type: application/json

{
  "address": "Ваши любимые продукты.ул.Ленина 30",
  "positions": [
    {
      "product": 24,
      "quantity": 256,
      "price": 123
    },
    {
      "product": 37,
      "quantity": 67,
      "price": 345
    }
  ]
}

###

# обновляем записи на складе
PATCH {{baseUrl}}/stocks/10/
Content-Type: application/json

{
  "positions": [
    {
      "product": 30,
      "quantity": 1000,
      "price": 780.80
    },
    {
      "product": 31,
      "quantity": 6200,
      "price": 12
    }
  ]
}

###

# поиск складов, где есть определенный продукт
GET {{baseUrl}}/stocks/?products=30
Content-Type: application/json

###

# поиск складов
GET {{baseUrl}}/stocks/
Content-Type: application/json

###

# поиск складов, где есть определенный продукт по названию
GET {{baseUrl}}/stocks/?search=клю
Content-Type: application/json
